"""empty message

Revision ID: 847ac50c61a9
Revises: 6e9c45925de5
Create Date: 2022-11-26 13:49:43.198450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847ac50c61a9'
down_revision = '6e9c45925de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
